#!/usr/bin/env bash
# ============================================================================
# check-schema-sync.sh
# ============================================================================
# CI guardrail. Enforces three-way agreement between:
#
#   1. SCHEMA.md                              (the human-readable narrative)
#   2. db/postgres/migrations/*.sql           (the historical migration record)
#   3. db/postgres/schema.sql                 (the UNIFIED source of truth)
#      + db/mysql/init/*.sql                  (MySQL FVP data source)
#
# Two checks:
#
#   A. The set of tables documented in SCHEMA.md must equal the set of tables
#      declared in the DDL (migrations + MySQL init).
#   B. The unified schema.sql must be a byte-exact match for the output of
#      scripts/generate-unified-schema.sh — i.e., schema.sql is the
#      concatenated migrations, regenerated. No hand-editing the unified file.
#
# Run locally before pushing, or rely on the CI workflow.
# ============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ----------------------------------------------------------------------------
# Check A — table-set agreement (SCHEMA.md <-> DDL)
# ----------------------------------------------------------------------------

declared_pg=$(
  awk '
    /^CREATE TABLE / {
      line = $0;
      sub(/^CREATE TABLE /, "", line);
      sub(/^IF NOT EXISTS /, "", line);
      n = split(line, parts, /[[:space:](]/);
      name = parts[1];
      if (name ~ /^(eh_control|eh_operational)\./) print name;
    }
  ' db/postgres/migrations/*.sql | sort -u
)

declared_mysql=$(
  awk '
    /^CREATE TABLE / {
      line = $0;
      sub(/^CREATE TABLE /, "", line);
      sub(/^IF NOT EXISTS /, "", line);
      n = split(line, parts, /[[:space:](]/);
      name = parts[1];
      if (name !~ /\./) print "eh_demo." name;
      else print name;
    }
  ' db/mysql/init/*.sql | sort -u
)

declared=$(printf '%s\n%s\n' "$declared_pg" "$declared_mysql" | sed '/^$/d' | sort -u)

documented=$(
  grep -hoE '\b(eh_control|eh_operational|eh_demo)\.[a-z_][a-z0-9_]*\b' SCHEMA.md \
    | grep -Ev '_$' \
    | sort -u
)

declared=$(
  printf '%s\n' "$declared" \
    | grep -Ev '_(default|[0-9]{4}_[0-9]{2})$' \
    || true
)

only_in_ddl=$(comm -23 <(printf '%s\n' "$declared") <(printf '%s\n' "$documented") || true)
only_in_doc=$(comm -13 <(printf '%s\n' "$declared") <(printf '%s\n' "$documented") || true)

failed=0

if [[ -n "$only_in_ddl" ]]; then
  echo "ERROR: tables declared in DDL but NOT documented in SCHEMA.md:"
  printf '  - %s\n' $only_in_ddl
  failed=1
fi

if [[ -n "$only_in_doc" ]]; then
  echo "ERROR: tables documented in SCHEMA.md but NOT declared in DDL:"
  printf '  - %s\n' $only_in_doc
  failed=1
fi

# ----------------------------------------------------------------------------
# Check B — unified schema.sql must equal the regenerated output
# ----------------------------------------------------------------------------

if [[ ! -f db/postgres/schema.sql ]]; then
  echo "ERROR: db/postgres/schema.sql is missing. Run: bash scripts/generate-unified-schema.sh"
  failed=1
else
  TMP=$(mktemp)
  trap 'rm -f "$TMP"' EXIT

  # Re-run the generator into a temp file.
  OUT=db/postgres/schema.sql
  EXPECTED="$TMP"

  # Reproduce the generator's output (without overwriting the committed file).
  {
    cat <<'HEAD'
-- ============================================================================
-- EventHorizon — Unified control-plane schema (auto-generated)
-- ============================================================================
-- GENERATED BY: scripts/generate-unified-schema.sh
-- DO NOT EDIT BY HAND. Edit the source migrations in db/postgres/migrations/
-- and re-run the generator. CI asserts this file matches the concatenation
-- of the migrations.
--
-- This file IS the source of truth for the EventHorizon control plane.
-- Apply it to a fresh Postgres 16+ database to create everything from
-- scratch:
--
--     psql -h localhost -U postgres -d eh_control_plane -f db/postgres/schema.sql
--
-- After applying, run db/postgres/init/zz_set_role_passwords.sh to attach
-- passwords to the eh_admin and eh_service roles from env-injected secrets.
--
-- Conventions enforced here (architecture §5.1, zero-trust §10/§13/§14):
--   * UUIDv7 primary keys (app-generated; no auto-increment anywhere).
--   * INSERT-only writes (eh_service grant excludes UPDATE/DELETE/DDL).
--   * SCD Type 2 triad (valid_from, valid_to, is_current) — set at insert,
--     never mutated.
--   * Broken-down typed columns; JSONB only for opaque payloads.
--   * Per-kind source_<kind> tables (the ProxySQL pattern).
--   * RLS forced on every tenant-scoped table.
-- ============================================================================

HEAD

    for f in db/postgres/migrations/*.sql; do
      name="$(basename "$f")"
      printf '\n-- ----------------------------------------------------------------------------\n-- BEGIN %s\n-- ----------------------------------------------------------------------------\n' "$name"
      cat "$f"
      printf -- '-- ----------------------------------------------------------------------------\n-- END %s\n-- ----------------------------------------------------------------------------\n' "$name"
    done

    cat <<'FOOT'

-- ============================================================================
-- End of unified schema. Apply 0013_set_role_passwords.sh next for role
-- password attachment.
-- ============================================================================
FOOT
  } > "$EXPECTED"

  if ! diff -q "$EXPECTED" "$OUT" >/dev/null; then
    echo "ERROR: db/postgres/schema.sql is OUT OF SYNC with db/postgres/migrations/."
    echo "       Run: bash scripts/generate-unified-schema.sh"
    echo "       First differing context:"
    diff "$EXPECTED" "$OUT" | head -30 | sed 's/^/         /'
    failed=1
  fi
fi

# ----------------------------------------------------------------------------
# Verdict
# ----------------------------------------------------------------------------

if [[ "$failed" -eq 0 ]]; then
  count=$(printf '%s\n' "$declared" | grep -c . || true)
  echo "OK: SCHEMA.md and DDL agree on $count tables; schema.sql matches migrations."
  exit 0
fi

echo ""
echo "Per zero-trust §11 (Schema-First, Code-After), SCHEMA.md, the migrations,"
echo "and the unified schema.sql must evolve together. Update them in the same PR;"
echo "the operator approves schema changes per-table."
exit 1
