#!/usr/bin/env bash
# ============================================================================
# generate-unified-schema.sh
# ============================================================================
# Concatenates db/postgres/migrations/*.sql into the canonical unified DDL at
# db/postgres/schema.sql. THAT FILE is the single-source-of-truth that an
# operator can run with `psql -f db/postgres/schema.sql` to recreate the
# entire EventHorizon control plane on a fresh database.
#
# The individual migration files stay in the repo as the historical record
# of how the schema evolved. The unified schema.sql and the migrations must
# agree (CI guardrail in scripts/check-schema-sync.sh).
#
# Usage:
#   bash scripts/generate-unified-schema.sh
# ============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="db/postgres/schema.sql"
mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<'HEAD'
-- ============================================================================
-- EventHorizon — Unified control-plane schema (auto-generated)
-- ============================================================================
-- GENERATED BY: scripts/generate-unified-schema.sh
-- DO NOT EDIT BY HAND. Edit the source migrations in db/postgres/migrations/
-- and re-run the generator. CI asserts this file matches the concatenation
-- of the migrations.
--
-- This file IS the source of truth for the EventHorizon control plane.
-- Apply it to a fresh Postgres 16+ database to create everything from
-- scratch:
--
--     psql -h localhost -U postgres -d eh_control_plane -f db/postgres/schema.sql
--
-- After applying, run db/postgres/init/zz_set_role_passwords.sh to attach
-- passwords to the eh_admin and eh_service roles from env-injected secrets.
--
-- Conventions enforced here (architecture §5.1, zero-trust §10/§13/§14):
--   * UUIDv7 primary keys (app-generated; no auto-increment anywhere).
--   * INSERT-only writes (eh_service grant excludes UPDATE/DELETE/DDL).
--   * SCD Type 2 triad (valid_from, valid_to, is_current) — set at insert,
--     never mutated.
--   * Broken-down typed columns; JSONB only for opaque payloads.
--   * Per-kind source_<kind> tables (the ProxySQL pattern).
--   * RLS forced on every tenant-scoped table.
-- ============================================================================

HEAD

for f in db/postgres/migrations/*.sql; do
    name="$(basename "$f")"
    cat >> "$OUT" <<EOF

-- ----------------------------------------------------------------------------
-- BEGIN ${name}
-- ----------------------------------------------------------------------------
EOF
    cat "$f" >> "$OUT"
    cat >> "$OUT" <<EOF
-- ----------------------------------------------------------------------------
-- END ${name}
-- ----------------------------------------------------------------------------
EOF
done

# Trailing footer.
cat >> "$OUT" <<'FOOT'

-- ============================================================================
-- End of unified schema. Apply 0013_set_role_passwords.sh next for role
-- password attachment.
-- ============================================================================
FOOT

echo "Generated $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, $(grep -c '^CREATE TABLE' "$OUT" | tr -d ' ') CREATE TABLE statements)"
