-- ============================================================================
-- EventHorizon — Unified control-plane schema (auto-generated)
-- ============================================================================
-- GENERATED BY: scripts/generate-unified-schema.sh
-- DO NOT EDIT BY HAND. Edit the source migrations in db/postgres/migrations/
-- and re-run the generator. CI asserts this file matches the concatenation
-- of the migrations.
--
-- This file IS the source of truth for the EventHorizon control plane.
-- Apply it to a fresh Postgres 16+ database to create everything from
-- scratch:
--
--     psql -h localhost -U postgres -d eh_control_plane -f db/postgres/schema.sql
--
-- After applying, run db/postgres/init/zz_set_role_passwords.sh to attach
-- passwords to the eh_admin and eh_service roles from env-injected secrets.
--
-- Conventions enforced here (architecture §5.1, zero-trust §10/§13/§14):
--   * UUIDv7 primary keys (app-generated; no auto-increment anywhere).
--   * INSERT-only writes (eh_service grant excludes UPDATE/DELETE/DDL).
--   * SCD Type 2 triad (valid_from, valid_to, is_current) — set at insert,
--     never mutated.
--   * Broken-down typed columns; JSONB only for opaque payloads.
--   * Per-kind source_<kind> tables (the ProxySQL pattern).
--   * RLS forced on every tenant-scoped table.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- BEGIN 0001_schemas_and_roles.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0001 — Schemas and roles
-- ============================================================================
-- Creates the two logical schemas (eh_control + eh_operational) and the two
-- application roles (eh_admin, eh_service). Default privileges are set so
-- every future table inherits the right grants without per-table GRANT
-- statements.
--
-- Reference: architecture §5.1–§5.10, SCHEMA.md §2, §5.
-- ============================================================================

-- 1. Schemas
-- ----------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS eh_control;
CREATE SCHEMA IF NOT EXISTS eh_operational;

COMMENT ON SCHEMA eh_control
  IS 'Config: agents, sources, entities, bindings, rules, policies. Small, slow-changing, operator-managed.';

COMMENT ON SCHEMA eh_operational
  IS 'Events: audit log, telemetry, health, drift, cost, proposals. Large, append-only, rebuildable from Kafka mirror.';

-- 2. Roles
-- ----------------------------------------------------------------------------
-- Role passwords are NOT set here. Operator sets them via secrets manager
-- and connects with the appropriate credentials. CREATE ROLE here only
-- declares the role identities.
-- ----------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'eh_admin') THEN
    CREATE ROLE eh_admin WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
    COMMENT ON ROLE eh_admin
      IS 'Operator-only role. Holds DDL + GRANT + REVOKE + migration authority. Application NEVER authenticates as this role (zero-trust §13).';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'eh_service') THEN
    CREATE ROLE eh_service WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
    COMMENT ON ROLE eh_service
      IS 'Application role. SELECT on eh_control; SELECT + INSERT on eh_operational. No UPDATE, no DELETE, no DDL — engine-refused.';
  END IF;
END
$$;

-- 3. Schema usage grants
-- ----------------------------------------------------------------------------

GRANT USAGE ON SCHEMA eh_control     TO eh_service;
GRANT USAGE ON SCHEMA eh_operational TO eh_service;

GRANT ALL    ON SCHEMA eh_control     TO eh_admin;
GRANT ALL    ON SCHEMA eh_operational TO eh_admin;

-- 4. Default privileges for FUTURE tables
-- ----------------------------------------------------------------------------
-- Every table created hereafter inherits these grants automatically.
-- This is what enforces "the app cannot UPDATE or DELETE" at the engine
-- level — eh_service simply has no UPDATE/DELETE privilege ever granted.
-- ----------------------------------------------------------------------------

-- eh_control: app gets SELECT only on every future table.
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_control
  GRANT SELECT ON TABLES TO eh_service;

-- eh_operational: app gets SELECT + INSERT only.
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_operational
  GRANT SELECT, INSERT ON TABLES TO eh_service;

-- Sequences (in case SCD2 chain-key sequences are added later — currently
-- everything uses UUIDv7 app-side, so no sequences are expected, but we
-- grant USAGE prophylactically for future flexibility).
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_control
  GRANT USAGE ON SEQUENCES TO eh_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_operational
  GRANT USAGE ON SEQUENCES TO eh_service;

-- Admin role gets everything on every future object.
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_control
  GRANT ALL ON TABLES TO eh_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_operational
  GRANT ALL ON TABLES TO eh_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_control
  GRANT ALL ON SEQUENCES TO eh_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA eh_operational
  GRANT ALL ON SEQUENCES TO eh_admin;

-- 5. Required extensions
-- ----------------------------------------------------------------------------

-- pgcrypto is used opportunistically (gen_random_uuid for emergencies);
-- UUIDv7 PKs are app-generated. This extension is broadly available on
-- managed Postgres providers.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 6. Session-variable contract for identity passthrough (§5.10, §7)
-- ----------------------------------------------------------------------------
-- The application sets `app.agent_id` and `app.tenant_id` per request via
-- `SET LOCAL` inside its transaction. RLS policies (migration 0011) read
-- these via current_setting() to filter rows. No object-level config needed
-- here — Postgres GUCs of the form `<namespace>.<name>` are accepted by
-- default; we just document the contract.
-- ----------------------------------------------------------------------------
-- ----------------------------------------------------------------------------
-- END 0001_schemas_and_roles.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0002_identity.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0002 — Identity & tenancy
-- ============================================================================
-- tenants, agents, agent_secrets — the identity spine.
--
-- Reference: SCHEMA.md §3.1–§3.3.
-- ============================================================================

-- 1. tenants
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.tenants (
  id                     UUID         NOT NULL,
  name                   TEXT         NOT NULL,
  display_name           TEXT         NOT NULL,
  status                 TEXT         NOT NULL DEFAULT 'active',
  data_db_uri_secret_ref TEXT,

  valid_from             TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to               TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current             BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT tenants_status_chk    CHECK (status IN ('active','suspended','retired')),
  CONSTRAINT tenants_valid_order   CHECK (valid_to >= valid_from)
);

CREATE INDEX tenants_name_current_idx
  ON eh_control.tenants (name)
  WHERE is_current = true;

CREATE INDEX tenants_chain_idx
  ON eh_control.tenants (name, valid_from DESC);

COMMENT ON TABLE eh_control.tenants
  IS 'Tenants. One physical database per tenant for data sources (architecture §5.8). SCD Type 2: INSERT-only, current = ORDER BY valid_from DESC LIMIT 1.';

-- 2. agents
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.agents (
  id                          UUID         NOT NULL,
  name                        TEXT         NOT NULL,
  tenant_id                   UUID         NOT NULL,
  owner_email                 TEXT         NOT NULL,
  status                      TEXT         NOT NULL DEFAULT 'active',
  cost_budget_cents_per_hour  BIGINT,

  valid_from                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to                    TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current                  BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT agents_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES eh_control.tenants(id),
  CONSTRAINT agents_status_chk
    CHECK (status IN ('active','disabled','retired')),
  CONSTRAINT agents_budget_nonneg
    CHECK (cost_budget_cents_per_hour IS NULL OR cost_budget_cents_per_hour >= 0),
  CONSTRAINT agents_valid_order
    CHECK (valid_to >= valid_from),
  CONSTRAINT agents_owner_email_basic
    CHECK (owner_email LIKE '%@%.%')
);

CREATE INDEX agents_tenant_name_current_idx
  ON eh_control.agents (tenant_id, name)
  WHERE is_current = true;

CREATE INDEX agents_chain_idx
  ON eh_control.agents (tenant_id, name, valid_from DESC);

COMMENT ON TABLE eh_control.agents
  IS 'Logical agents. SCD Type 2. Identity propagates to backends via SET LOCAL app.agent_id (architecture §8).';

-- 3. agent_secrets
-- ----------------------------------------------------------------------------
-- Split from agents so its row-level grants can be tighter (the eh_service
-- account reads this only inside the authn path, never broadly).
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.agent_secrets (
  id          UUID         NOT NULL,
  agent_id    UUID         NOT NULL,
  token_hash  TEXT         NOT NULL,
  token_kind  TEXT         NOT NULL,
  revoked_at  TIMESTAMPTZ,

  valid_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to    TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current  BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT agent_secrets_agent_fk
    FOREIGN KEY (agent_id) REFERENCES eh_control.agents(id),
  CONSTRAINT agent_secrets_kind_chk
    CHECK (token_kind IN ('static','jwt','mtls_fingerprint')),
  CONSTRAINT agent_secrets_hash_len
    CHECK (length(token_hash) >= 32),
  CONSTRAINT agent_secrets_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX agent_secrets_agent_active_idx
  ON eh_control.agent_secrets (agent_id)
  WHERE is_current = true AND revoked_at IS NULL;

COMMENT ON TABLE eh_control.agent_secrets
  IS 'Token hashes for agent auth. Revocation is a NEW row with revoked_at set; original row is never updated (zero-trust §10).';
-- ----------------------------------------------------------------------------
-- END 0002_identity.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0003_authorization.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0003 — Authorization
-- ============================================================================
-- policies (Cedar policy text), capabilities ((agent, entity, action) grants).
--
-- Reference: SCHEMA.md §3.3, §3.4. Architecture §8.
-- ============================================================================

-- 1. policies
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.policies (
  id              UUID         NOT NULL,
  tenant_id       UUID         NOT NULL,
  name            TEXT         NOT NULL,
  body            TEXT         NOT NULL,
  compiled_hash   TEXT         NOT NULL,

  valid_from      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to        TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current      BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT policies_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES eh_control.tenants(id),
  CONSTRAINT policies_body_nonempty
    CHECK (length(body) > 0),
  CONSTRAINT policies_hash_sha256
    CHECK (compiled_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT policies_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX policies_tenant_name_current_idx
  ON eh_control.policies (tenant_id, name)
  WHERE is_current = true;

CREATE INDEX policies_chain_idx
  ON eh_control.policies (tenant_id, name, valid_from DESC);

COMMENT ON TABLE eh_control.policies
  IS 'Cedar policy text, version-tagged. compiled_hash is sha256 of the Cedar AST for cache invalidation.';

-- 2. capabilities
-- ----------------------------------------------------------------------------
-- (agent, entity, action) grants. Optional condition_policy_id references a
-- Cedar policy that further restricts the grant (e.g. "only for tenant_id =
-- the agent's tenant" or "only when context.window <= 90d").
-- ----------------------------------------------------------------------------

-- Note: entities table is defined in migration 0006; we use a NOT VALID FK
-- here for ordering, then VALIDATE in 0006. Postgres requires the referenced
-- table to exist at CREATE time, so the FK is added in 0006 after entities
-- is in place. For now, entity_id is an unconstrained UUID column; the FK
-- constraint is attached in 0006.

CREATE TABLE eh_control.capabilities (
  id                    UUID         NOT NULL,
  agent_id              UUID         NOT NULL,
  entity_id             UUID         NOT NULL,
  action                TEXT         NOT NULL,
  condition_policy_id   UUID,

  valid_from            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to              TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current            BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT capabilities_agent_fk
    FOREIGN KEY (agent_id) REFERENCES eh_control.agents(id),
  CONSTRAINT capabilities_policy_fk
    FOREIGN KEY (condition_policy_id) REFERENCES eh_control.policies(id),
  CONSTRAINT capabilities_action_chk
    CHECK (action IN ('read','append','update','delete')),
  CONSTRAINT capabilities_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX capabilities_agent_current_idx
  ON eh_control.capabilities (agent_id)
  WHERE is_current = true;

CREATE INDEX capabilities_entity_action_idx
  ON eh_control.capabilities (entity_id, action)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.capabilities
  IS '(agent, entity, action) grants. Cedar policy referenced via condition_policy_id can further restrict; absent = unconditional grant.';
-- ----------------------------------------------------------------------------
-- END 0003_authorization.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0004_sources_core.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0004 — Sources (kind-agnostic core)
-- ============================================================================
-- sources (the registry) + source_credentials (refs to secrets manager).
-- Per-kind tables are in 0005.
--
-- Reference: SCHEMA.md §3.5, §3.6.
-- ============================================================================

-- 1. sources
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.sources (
  id              UUID         NOT NULL,
  tenant_id       UUID         NOT NULL,
  name            TEXT         NOT NULL,
  kind            TEXT         NOT NULL,
  ring            TEXT         NOT NULL DEFAULT 'staging',
  status          TEXT         NOT NULL DEFAULT 'registered',
  last_health_at  TIMESTAMPTZ,

  valid_from      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to        TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current      BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT sources_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES eh_control.tenants(id),
  CONSTRAINT sources_kind_chk
    CHECK (kind IN ('mysql','postgres','iceberg','duckdb','rag','model','file','snowflake','mssql')),
  CONSTRAINT sources_ring_chk
    CHECK (ring IN ('staging','production','retired')),
  CONSTRAINT sources_status_chk
    CHECK (status IN ('registered','probed','bound','staging','production','disabled','error')),
  CONSTRAINT sources_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX sources_tenant_name_current_idx
  ON eh_control.sources (tenant_id, name)
  WHERE is_current = true;

CREATE INDEX sources_kind_status_idx
  ON eh_control.sources (kind, status)
  WHERE is_current = true;

CREATE INDEX sources_chain_idx
  ON eh_control.sources (tenant_id, name, valid_from DESC);

COMMENT ON TABLE eh_control.sources
  IS 'Registered backends, kind-agnostic columns. Per-kind typed config lives in source_<kind> tables — the ProxySQL pattern (architecture §5.3, §5.6).';
COMMENT ON COLUMN eh_control.sources.kind
  IS 'Extending this enum is an operator-approved migration (zero-trust §7, §11).';

-- 2. source_credentials
-- ----------------------------------------------------------------------------
-- Refs only. Values NEVER stored here.
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.source_credentials (
  id          UUID         NOT NULL,
  source_id   UUID         NOT NULL,
  purpose     TEXT         NOT NULL,
  secret_ref  TEXT         NOT NULL,

  valid_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to    TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current  BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT source_credentials_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_credentials_purpose_chk
    CHECK (purpose IN ('username','password','token','tls_cert','tls_key','api_key')),
  CONSTRAINT source_credentials_ref_scheme
    CHECK (secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_credentials_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX source_credentials_source_idx
  ON eh_control.source_credentials (source_id, purpose)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.source_credentials
  IS 'References to secrets manager (Vault, k8s Secret, AWS/GCP Secrets Manager). VALUES are NEVER stored.';
-- ----------------------------------------------------------------------------
-- END 0004_sources_core.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0005_source_kinds.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0005 — Per-connector typed config tables (the ProxySQL pattern)
-- ============================================================================
-- One typed config table per connector kind. FK 1:1 to sources(id).
-- Adding a new connector kind = new migration adding source_<kind> +
-- extending sources.kind CHECK enum.
--
-- Reference: SCHEMA.md §3.7.
-- ============================================================================

-- Helper macro (textual): every source_<kind> table has the same SCD2 triad
-- and the same source_id PK+FK structure. Tables are written out explicitly
-- because Postgres doesn't have a clean template mechanism for table DDL.

-- ============================================================================
-- 1. source_mysql (Phase 1 FVP target)
-- ============================================================================

CREATE TABLE eh_control.source_mysql (
  source_id            UUID         NOT NULL,
  host                 TEXT         NOT NULL,
  port                 INT          NOT NULL DEFAULT 3306,
  database_name        TEXT         NOT NULL,
  username_secret_ref  TEXT         NOT NULL,
  password_secret_ref  TEXT         NOT NULL,
  ssl_mode             TEXT         NOT NULL DEFAULT 'preferred',
  max_pool_size        INT          NOT NULL DEFAULT 8,

  valid_from           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to             TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current           BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_mysql_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_mysql_port_range
    CHECK (port BETWEEN 1 AND 65535),
  CONSTRAINT source_mysql_pool_pos
    CHECK (max_pool_size > 0),
  CONSTRAINT source_mysql_ssl_chk
    CHECK (ssl_mode IN ('disabled','preferred','required','verify_ca','verify_identity')),
  CONSTRAINT source_mysql_secret_ref_username
    CHECK (username_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_mysql_secret_ref_password
    CHECK (password_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_mysql_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_mysql
  IS 'MySQL connector config. 1:1 with sources where kind=''mysql''.';

-- ============================================================================
-- 2. source_postgres
-- ============================================================================

CREATE TABLE eh_control.source_postgres (
  source_id            UUID         NOT NULL,
  host                 TEXT         NOT NULL,
  port                 INT          NOT NULL DEFAULT 5432,
  database_name        TEXT         NOT NULL,
  username_secret_ref  TEXT         NOT NULL,
  password_secret_ref  TEXT         NOT NULL,
  application_name     TEXT         NOT NULL DEFAULT 'eventhorizon',
  ssl_mode             TEXT         NOT NULL DEFAULT 'require',
  max_pool_size        INT          NOT NULL DEFAULT 8,

  valid_from           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to             TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current           BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_postgres_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_postgres_port_range
    CHECK (port BETWEEN 1 AND 65535),
  CONSTRAINT source_postgres_pool_pos
    CHECK (max_pool_size > 0),
  CONSTRAINT source_postgres_ssl_chk
    CHECK (ssl_mode IN ('disable','allow','prefer','require','verify-ca','verify-full')),
  CONSTRAINT source_postgres_secret_ref_username
    CHECK (username_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_postgres_secret_ref_password
    CHECK (password_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_postgres_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_postgres
  IS 'Postgres connector config. 1:1 with sources where kind=''postgres''.';

-- ============================================================================
-- 3. source_iceberg
-- ============================================================================

CREATE TABLE eh_control.source_iceberg (
  source_id          UUID         NOT NULL,
  catalog_uri        TEXT         NOT NULL,
  namespace          TEXT         NOT NULL,
  warehouse          TEXT         NOT NULL,
  auth_kind          TEXT         NOT NULL DEFAULT 'none',
  auth_secret_ref    TEXT,

  valid_from         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to           TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current         BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_iceberg_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_iceberg_auth_chk
    CHECK (auth_kind IN ('none','oauth','sigv4','token')),
  CONSTRAINT source_iceberg_secret_ref_match
    CHECK (
      (auth_kind = 'none' AND auth_secret_ref IS NULL)
      OR
      (auth_kind <> 'none' AND auth_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
    ),
  CONSTRAINT source_iceberg_catalog_uri_scheme
    CHECK (catalog_uri ~ '^(rest|hive|s3|file|gs|hdfs)://'),
  CONSTRAINT source_iceberg_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_iceberg
  IS 'Apache Iceberg connector config. 1:1 with sources where kind=''iceberg''.';

-- ============================================================================
-- 4. source_duckdb
-- ============================================================================

CREATE TABLE eh_control.source_duckdb (
  source_id      UUID         NOT NULL,
  database_path  TEXT         NOT NULL DEFAULT ':memory:',

  valid_from     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to       TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current     BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_duckdb_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_duckdb_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_duckdb
  IS 'DuckDB connector config (in-memory or file-backed). 1:1 with sources where kind=''duckdb''. Multi-valued extensions are normalized into source_duckdb_extensions (4NF).';

-- 4a. source_duckdb_extensions (4NF normalization of source_duckdb.extensions)
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.source_duckdb_extensions (
  id              UUID         NOT NULL,
  source_id       UUID         NOT NULL,
  extension_name  TEXT         NOT NULL,
  position        INT          NOT NULL DEFAULT 0,

  valid_from      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to        TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current      BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT source_duckdb_extensions_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.source_duckdb(source_id),
  CONSTRAINT source_duckdb_extensions_name_basic
    CHECK (extension_name ~ '^[a-z][a-z0-9_]{0,62}$'),
  CONSTRAINT source_duckdb_extensions_position_nonneg
    CHECK (position >= 0),
  CONSTRAINT source_duckdb_extensions_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX source_duckdb_extensions_source_idx
  ON eh_control.source_duckdb_extensions (source_id, position)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.source_duckdb_extensions
  IS 'DuckDB extensions to load per source. 4NF-normalised from what was previously a TEXT[] column.';

-- ============================================================================
-- 5. source_rag (forward-looking)
-- ============================================================================

CREATE TABLE eh_control.source_rag (
  source_id          UUID         NOT NULL,
  vector_store_uri   TEXT         NOT NULL,
  embedding_model    TEXT         NOT NULL,
  top_k_default      INT          NOT NULL DEFAULT 8,
  auth_secret_ref    TEXT,

  valid_from         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to           TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current         BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_rag_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_rag_top_k_pos
    CHECK (top_k_default > 0),
  CONSTRAINT source_rag_secret_ref_scheme
    CHECK (auth_secret_ref IS NULL OR auth_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_rag_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_rag
  IS 'RAG / vector-store connector config (forward-looking, Phase 13+).';

-- ============================================================================
-- 6. source_model (forward-looking)
-- ============================================================================

CREATE TABLE eh_control.source_model (
  source_id            UUID         NOT NULL,
  provider             TEXT         NOT NULL,
  model_id             TEXT         NOT NULL,
  api_key_secret_ref   TEXT         NOT NULL,
  max_tokens_default   INT          NOT NULL DEFAULT 1024,

  valid_from           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to             TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current           BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_model_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_model_provider_chk
    CHECK (provider IN ('anthropic','openai','mistral','local')),
  CONSTRAINT source_model_max_tokens_pos
    CHECK (max_tokens_default > 0),
  CONSTRAINT source_model_secret_ref_scheme
    CHECK (api_key_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_model_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_model
  IS 'Model / LLM connector config (forward-looking, Phase 13+).';

-- ============================================================================
-- 7. source_file (forward-looking)
-- ============================================================================

CREATE TABLE eh_control.source_file (
  source_id           UUID         NOT NULL,
  root_path           TEXT         NOT NULL,
  format              TEXT         NOT NULL,
  partition_pattern   TEXT,

  valid_from          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to            TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current          BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_file_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_file_format_chk
    CHECK (format IN ('parquet','csv','json','jsonl','arrow_ipc')),
  CONSTRAINT source_file_root_path_scheme
    CHECK (root_path ~ '^(file|s3|gs|hdfs|azure)://'),
  CONSTRAINT source_file_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_file
  IS 'File-tree connector config (Parquet/CSV/JSON over object storage or local).';

-- ============================================================================
-- 8. source_snowflake (Phase 12, V1.1)
-- ============================================================================

CREATE TABLE eh_control.source_snowflake (
  source_id         UUID         NOT NULL,
  account           TEXT         NOT NULL,
  warehouse         TEXT         NOT NULL,
  database_name     TEXT         NOT NULL,
  schema_name       TEXT         NOT NULL,
  auth_kind         TEXT         NOT NULL DEFAULT 'key_pair',
  auth_secret_ref   TEXT         NOT NULL,

  valid_from        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to          TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current        BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_snowflake_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_snowflake_auth_chk
    CHECK (auth_kind IN ('password','key_pair','oauth')),
  CONSTRAINT source_snowflake_secret_ref_scheme
    CHECK (auth_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'),
  CONSTRAINT source_snowflake_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_snowflake
  IS 'Snowflake connector config (ADBC-backed, Phase 12 V1.1).';

-- ============================================================================
-- 9. source_mssql (Phase 12, V1.1)
-- ============================================================================

CREATE TABLE eh_control.source_mssql (
  source_id            UUID         NOT NULL,
  host                 TEXT         NOT NULL,
  port                 INT          NOT NULL DEFAULT 1433,
  instance             TEXT,
  database_name        TEXT         NOT NULL,
  auth_kind            TEXT         NOT NULL DEFAULT 'sql',
  username_secret_ref  TEXT,
  password_secret_ref  TEXT,

  valid_from           TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to             TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current           BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (source_id),
  CONSTRAINT source_mssql_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT source_mssql_port_range
    CHECK (port BETWEEN 1 AND 65535),
  CONSTRAINT source_mssql_auth_chk
    CHECK (auth_kind IN ('sql','integrated','aad')),
  CONSTRAINT source_mssql_secret_match
    CHECK (
      (auth_kind = 'integrated' AND username_secret_ref IS NULL AND password_secret_ref IS NULL)
      OR
      (auth_kind <> 'integrated'
         AND username_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://'
         AND password_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
    ),
  CONSTRAINT source_mssql_valid_order
    CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE eh_control.source_mssql
  IS 'SQL Server connector config (tiberius-backed, Phase 12 V1.1).';
-- ----------------------------------------------------------------------------
-- END 0005_source_kinds.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0006_semantic_schema.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0006 — Semantic schema
-- ============================================================================
-- entities (agent-facing concepts) + entity_fields (their typed attributes).
-- Also adds the FK from capabilities(entity_id) → entities(id), deferred from
-- 0003 because of table ordering.
--
-- Reference: SCHEMA.md §3.8, §3.9.
-- ============================================================================

-- 1. entities
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.entities (
  id              UUID         NOT NULL,
  tenant_id       UUID         NOT NULL,
  kind            TEXT         NOT NULL DEFAULT 'data',
  name            TEXT         NOT NULL,
  description     TEXT,
  entity_version  INT          NOT NULL DEFAULT 1,

  valid_from      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to        TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current      BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entities_tenant_fk
    FOREIGN KEY (tenant_id) REFERENCES eh_control.tenants(id),
  CONSTRAINT entities_kind_chk
    CHECK (kind IN ('data','control','derived','event')),
  CONSTRAINT entities_version_pos
    CHECK (entity_version >= 1),
  CONSTRAINT entities_name_basic
    CHECK (name ~ '^[A-Za-z][A-Za-z0-9_]{0,62}$'),
  CONSTRAINT entities_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entities_tenant_name_current_idx
  ON eh_control.entities (tenant_id, name)
  WHERE is_current = true;

CREATE INDEX entities_kind_idx
  ON eh_control.entities (kind)
  WHERE is_current = true;

CREATE INDEX entities_chain_idx
  ON eh_control.entities (tenant_id, name, valid_from DESC);

COMMENT ON TABLE eh_control.entities
  IS 'Agent-facing semantic entities. kind=''data'' for tenant data entities (Customer, Order); kind=''control'' for control-plane objects exposed via admin (Source, Binding); kind=''derived'' for materialised views; kind=''event'' for stream-shaped concepts.';

-- 2. entity_fields
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.entity_fields (
  id          UUID         NOT NULL,
  entity_id   UUID         NOT NULL,
  name        TEXT         NOT NULL,
  data_type   TEXT         NOT NULL,
  nullable    BOOLEAN      NOT NULL DEFAULT false,
  pii_flag    BOOLEAN      NOT NULL DEFAULT false,
  position    INT          NOT NULL DEFAULT 0,

  valid_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to    TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current  BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entity_fields_entity_fk
    FOREIGN KEY (entity_id) REFERENCES eh_control.entities(id),
  CONSTRAINT entity_fields_data_type_chk
    CHECK (data_type IN ('string','text','int','bigint','decimal','float','bool','uuid','timestamp','json','binary')),
  CONSTRAINT entity_fields_name_basic
    CHECK (name ~ '^[a-z][a-z0-9_]{0,62}$'),
  CONSTRAINT entity_fields_position_nonneg
    CHECK (position >= 0),
  CONSTRAINT entity_fields_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entity_fields_entity_position_idx
  ON eh_control.entity_fields (entity_id, position)
  WHERE is_current = true;

CREATE INDEX entity_fields_entity_name_current_idx
  ON eh_control.entity_fields (entity_id, name)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.entity_fields
  IS 'Typed field declarations per entity. Sub-entity of entities.';

-- 3. Deferred FK: capabilities.entity_id → entities.id
-- ----------------------------------------------------------------------------

ALTER TABLE eh_control.capabilities
  ADD CONSTRAINT capabilities_entity_fk
    FOREIGN KEY (entity_id) REFERENCES eh_control.entities(id);
-- ----------------------------------------------------------------------------
-- END 0006_semantic_schema.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0007_bindings_routing.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0007 — Bindings, routing rules, predicate AST
-- ============================================================================
-- entity_bindings (entity → source), entity_field_bindings (field → column),
-- routing_rules (priority-ordered), predicate_nodes (typed AST).
--
-- Reference: SCHEMA.md §3.10, §3.11, §3.12.
-- ============================================================================

-- 1. entity_bindings
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.entity_bindings (
  id                       UUID         NOT NULL,
  entity_id                UUID         NOT NULL,
  source_id                UUID         NOT NULL,
  physical_table           TEXT         NOT NULL,
  profile                  TEXT         NOT NULL DEFAULT 'oltp',
  lifecycle_state          TEXT         NOT NULL DEFAULT 'bound',
  shadow_traffic_percent   INT          NOT NULL DEFAULT 0,

  valid_from               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to                 TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current               BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entity_bindings_entity_fk
    FOREIGN KEY (entity_id) REFERENCES eh_control.entities(id),
  CONSTRAINT entity_bindings_source_fk
    FOREIGN KEY (source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT entity_bindings_profile_chk
    CHECK (profile IN ('oltp','analytical','archival','similarity')),
  CONSTRAINT entity_bindings_lifecycle_chk
    CHECK (lifecycle_state IN ('bound','staging','shadow','production','retired')),
  CONSTRAINT entity_bindings_shadow_pct_range
    CHECK (shadow_traffic_percent BETWEEN 0 AND 100),
  CONSTRAINT entity_bindings_table_basic
    CHECK (physical_table ~ '^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)?$'),
  CONSTRAINT entity_bindings_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entity_bindings_entity_idx
  ON eh_control.entity_bindings (entity_id)
  WHERE is_current = true;

CREATE INDEX entity_bindings_source_idx
  ON eh_control.entity_bindings (source_id)
  WHERE is_current = true;

CREATE INDEX entity_bindings_profile_idx
  ON eh_control.entity_bindings (entity_id, profile)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.entity_bindings
  IS 'Maps a logical entity to a physical table in a specific source. Per-binding allowed actions live in entity_binding_actions (4NF). Per-field column mappings live in entity_field_bindings.';

-- 1a. entity_binding_actions (4NF normalization of entity_bindings.supported_actions)
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.entity_binding_actions (
  id           UUID         NOT NULL,
  binding_id   UUID         NOT NULL,
  action       TEXT         NOT NULL,

  valid_from   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to     TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current   BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entity_binding_actions_binding_fk
    FOREIGN KEY (binding_id) REFERENCES eh_control.entity_bindings(id),
  CONSTRAINT entity_binding_actions_action_chk
    CHECK (action IN ('read','append','update','delete')),
  CONSTRAINT entity_binding_actions_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entity_binding_actions_binding_idx
  ON eh_control.entity_binding_actions (binding_id, action)
  WHERE is_current = true;

CREATE INDEX entity_binding_actions_action_idx
  ON eh_control.entity_binding_actions (action)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.entity_binding_actions
  IS 'Per-binding allowed actions (4NF-normalised from what was previously a TEXT[] column). Enables future per-action attributes (rate limits, cost overrides) without schema churn.';

-- 2. entity_field_bindings
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.entity_field_bindings (
  id                UUID         NOT NULL,
  binding_id        UUID         NOT NULL,
  entity_field_id   UUID         NOT NULL,
  physical_column   TEXT         NOT NULL,
  transform         TEXT,

  valid_from        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to          TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current        BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entity_field_bindings_binding_fk
    FOREIGN KEY (binding_id) REFERENCES eh_control.entity_bindings(id),
  CONSTRAINT entity_field_bindings_field_fk
    FOREIGN KEY (entity_field_id) REFERENCES eh_control.entity_fields(id),
  CONSTRAINT entity_field_bindings_column_basic
    CHECK (physical_column ~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$'),
  CONSTRAINT entity_field_bindings_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entity_field_bindings_binding_idx
  ON eh_control.entity_field_bindings (binding_id)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.entity_field_bindings
  IS 'Maps logical entity_fields to physical columns within a binding. Optional transform expression for future use (Phase 7+).';

-- 3. routing_rules
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.routing_rules (
  id                  UUID         NOT NULL,
  entity_id           UUID         NOT NULL,
  priority            INT          NOT NULL DEFAULT 100,
  target_source_id    UUID         NOT NULL,
  target_binding_id   UUID         NOT NULL,
  predicate_root_id   UUID,

  valid_from          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to            TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current          BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT routing_rules_entity_fk
    FOREIGN KEY (entity_id) REFERENCES eh_control.entities(id),
  CONSTRAINT routing_rules_source_fk
    FOREIGN KEY (target_source_id) REFERENCES eh_control.sources(id),
  CONSTRAINT routing_rules_binding_fk
    FOREIGN KEY (target_binding_id) REFERENCES eh_control.entity_bindings(id),
  CONSTRAINT routing_rules_priority_nonneg
    CHECK (priority >= 0),
  CONSTRAINT routing_rules_valid_order
    CHECK (valid_to >= valid_from)
  -- predicate_root_id FK is added below after predicate_nodes is created.
);

CREATE INDEX routing_rules_entity_priority_idx
  ON eh_control.routing_rules (entity_id, priority)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.routing_rules
  IS 'Declarative routes from (entity, conditions) → (source, binding). Evaluated in ascending priority. NULL predicate_root_id = unconditional default.';

-- 4. predicate_nodes
-- ----------------------------------------------------------------------------

CREATE TABLE eh_control.predicate_nodes (
  id          UUID         NOT NULL,
  rule_id     UUID         NOT NULL,
  parent_id   UUID,
  position    INT          NOT NULL DEFAULT 0,
  node_kind   TEXT         NOT NULL,
  left_key    TEXT,
  operator    TEXT,
  value_type  TEXT,
  value_text  TEXT,

  valid_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to    TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current  BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT predicate_nodes_rule_fk
    FOREIGN KEY (rule_id) REFERENCES eh_control.routing_rules(id),
  CONSTRAINT predicate_nodes_parent_fk
    FOREIGN KEY (parent_id) REFERENCES eh_control.predicate_nodes(id),
  CONSTRAINT predicate_nodes_kind_chk
    CHECK (node_kind IN ('and','or','not','compare','in','matches')),
  CONSTRAINT predicate_nodes_operator_chk
    CHECK (operator IS NULL OR operator IN ('=','!=','<','<=','>','>=','in','matches')),
  CONSTRAINT predicate_nodes_value_type_chk
    CHECK (value_type IS NULL OR value_type IN ('string','int','duration','enum_list')),
  CONSTRAINT predicate_nodes_position_nonneg
    CHECK (position >= 0),
  CONSTRAINT predicate_nodes_valid_order
    CHECK (valid_to >= valid_from),
  -- Shape constraint: inner nodes (and/or/not) have NULL leaf attrs; leaves
  -- (compare/in/matches) have NOT NULL leaf attrs.
  CONSTRAINT predicate_nodes_shape_chk CHECK (
    (
      node_kind IN ('and','or','not')
      AND left_key   IS NULL
      AND operator   IS NULL
      AND value_type IS NULL
      AND value_text IS NULL
    )
    OR
    (
      node_kind IN ('compare','in','matches')
      AND left_key   IS NOT NULL
      AND operator   IS NOT NULL
      AND value_type IS NOT NULL
      AND value_text IS NOT NULL
    )
  )
);

CREATE INDEX predicate_nodes_rule_idx
  ON eh_control.predicate_nodes (rule_id)
  WHERE is_current = true;

CREATE INDEX predicate_nodes_parent_idx
  ON eh_control.predicate_nodes (parent_id)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.predicate_nodes
  IS 'Routing predicate AST as a parent-child tree. Inner nodes (and/or/not) have child rows; leaves (compare/in/matches) carry typed left/op/value triples. Shape CHECK enforces correctness.';

-- 5. Deferred FK: routing_rules.predicate_root_id → predicate_nodes.id
-- ----------------------------------------------------------------------------

ALTER TABLE eh_control.routing_rules
  ADD CONSTRAINT routing_rules_predicate_root_fk
    FOREIGN KEY (predicate_root_id) REFERENCES eh_control.predicate_nodes(id);
-- ----------------------------------------------------------------------------
-- END 0007_bindings_routing.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0008_entity_relationships.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0008 — Entity relationships (the explicit graph index)
-- ============================================================================
-- Generic typed edges between any two control-plane entities. Indexes the
-- graph that the FKs in 0002–0007 already form, so traversal queries
-- ("what depends on X?", "what's downstream of Y?") become single SQL queries
-- alongside the typed per-kind tables.
--
-- Reference: SCHEMA.md §3.13. Architecture §5.13.
-- ============================================================================

CREATE TABLE eh_control.entity_relationships (
  id              UUID         NOT NULL,
  from_id         UUID         NOT NULL,
  from_kind       TEXT         NOT NULL,
  to_id           UUID         NOT NULL,
  to_kind         TEXT         NOT NULL,
  relation_kind   TEXT         NOT NULL,
  attrs           JSONB,

  valid_from      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  valid_to        TIMESTAMPTZ  NOT NULL DEFAULT 'infinity',
  is_current      BOOLEAN      NOT NULL DEFAULT true,

  PRIMARY KEY (id),
  CONSTRAINT entity_relationships_from_kind_chk
    CHECK (from_kind IN ('agent','source','entity','binding','policy','capability','rule','connector')),
  CONSTRAINT entity_relationships_to_kind_chk
    CHECK (to_kind   IN ('agent','source','entity','binding','policy','capability','rule','connector')),
  CONSTRAINT entity_relationships_relation_kind_chk
    CHECK (relation_kind IN ('depends_on','routes_to','owns','extends','authorizes','derives_from','observes')),
  CONSTRAINT entity_relationships_not_self
    CHECK (from_id <> to_id OR from_kind <> to_kind),
  CONSTRAINT entity_relationships_valid_order
    CHECK (valid_to >= valid_from)
);

CREATE INDEX entity_relationships_from_idx
  ON eh_control.entity_relationships (from_id, relation_kind)
  WHERE is_current = true;

CREATE INDEX entity_relationships_to_idx
  ON eh_control.entity_relationships (to_id, relation_kind)
  WHERE is_current = true;

CREATE INDEX entity_relationships_kind_pair_idx
  ON eh_control.entity_relationships (from_kind, to_kind, relation_kind)
  WHERE is_current = true;

COMMENT ON TABLE eh_control.entity_relationships
  IS 'Explicit graph index of typed edges between any two control-plane entities. Indexes the FK graph; does NOT replace typed per-kind tables. New relation kinds = operator-approved migration extending the CHECK enum.';

COMMENT ON COLUMN eh_control.entity_relationships.attrs
  IS 'Narrow JSONB tail for relation-specific extras only. Cross-cutting fields stay typed.';
-- ----------------------------------------------------------------------------
-- END 0008_entity_relationships.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0009_operational_audit.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0009 — Operational: audit_log (durable per-intent record)
-- ============================================================================
-- Time-partitioned monthly. Append-only. The PG audit sink writes one row per
-- intent transactionally before the HTTP response returns. If audit write
-- fails, the request fails (architecture §10).
--
-- Reference: SCHEMA.md §4.1.
-- ============================================================================

-- 1. Partitioned parent
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.audit_log (
  id               UUID         NOT NULL,
  ts               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  trace_id         UUID         NOT NULL,
  tenant_id        UUID         NOT NULL,
  agent_id         UUID         NOT NULL,
  entity_id        UUID,
  source_id        UUID,
  connector_kind   TEXT,
  action           TEXT         NOT NULL,
  plan_hash        TEXT,
  decision         TEXT         NOT NULL,
  outcome          TEXT         NOT NULL,
  latency_ms       INT          NOT NULL,
  est_bytes        BIGINT,
  actual_bytes     BIGINT,
  raw_intent       JSONB        NOT NULL,

  PRIMARY KEY (ts, id),    -- partition key first per PG requirement
  CONSTRAINT audit_log_action_chk
    CHECK (action IN ('read','append','update','delete')),
  CONSTRAINT audit_log_decision_chk
    CHECK (decision IN ('permit','deny')),
  CONSTRAINT audit_log_outcome_chk
    CHECK (outcome IN ('ok','denied','over_budget','circuit_open','plan_error','exec_error')),
  CONSTRAINT audit_log_connector_kind_chk
    CHECK (connector_kind IS NULL OR connector_kind IN
      ('mysql','postgres','iceberg','duckdb','rag','model','file','snowflake','mssql')),
  CONSTRAINT audit_log_latency_nonneg
    CHECK (latency_ms >= 0),
  CONSTRAINT audit_log_bytes_nonneg
    CHECK (
      (est_bytes    IS NULL OR est_bytes    >= 0)
      AND (actual_bytes IS NULL OR actual_bytes >= 0)
    ),
  CONSTRAINT audit_log_plan_hash_format
    CHECK (plan_hash IS NULL OR plan_hash ~ '^[0-9a-f]{64}$')
) PARTITION BY RANGE (ts);

COMMENT ON TABLE eh_operational.audit_log
  IS 'Durable per-intent audit record. Time-partitioned monthly. Append-only. PG audit sink writes one row transactionally; audit failure fails the request.';

CREATE INDEX audit_log_brin_ts_idx
  ON eh_operational.audit_log USING BRIN (ts);

CREATE INDEX audit_log_tenant_ts_idx
  ON eh_operational.audit_log (tenant_id, ts DESC);

CREATE INDEX audit_log_trace_idx
  ON eh_operational.audit_log (trace_id);

-- 2. Bootstrap partition (current month) and a default catch-all
-- ----------------------------------------------------------------------------
-- The operator (or a scheduled job) creates next month's partition before
-- it's needed. The default partition catches anything that lands outside
-- declared ranges (should be rare; surfaces config drift).
--
-- Bootstrap partition for May 2026 (current month in this initial commit).
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.audit_log_2026_05
  PARTITION OF eh_operational.audit_log
  FOR VALUES FROM ('2026-05-01 00:00:00+00') TO ('2026-06-01 00:00:00+00');

CREATE TABLE eh_operational.audit_log_default
  PARTITION OF eh_operational.audit_log
  DEFAULT;

COMMENT ON TABLE eh_operational.audit_log_default
  IS 'Catch-all partition. Rows landing here indicate missing forward partition — alert and roll a new partition.';
-- ----------------------------------------------------------------------------
-- END 0009_operational_audit.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0010_operational_other.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0010 — Operational: telemetry_events, source_health, schema_snapshots,
--                     cost_records, proposals
-- ============================================================================
-- The unified telemetry stream + supporting event tables. Per architecture
-- §10.1: one canonical stream, dimensioned, never per-connector schemas.
--
-- Reference: SCHEMA.md §4.2 – §4.3.
-- ============================================================================

-- 1. telemetry_events — partitioned monthly
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.telemetry_events (
  id               UUID         NOT NULL,
  ts               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  trace_id         UUID         NOT NULL,
  tenant_id        UUID         NOT NULL,
  agent_id         UUID,
  source_id        UUID,
  connector_kind   TEXT,
  entity_id        UUID,
  action           TEXT,
  event_kind       TEXT         NOT NULL,
  status           TEXT,
  latency_ms       INT,
  est_bytes        BIGINT,
  actual_bytes     BIGINT,
  tail             JSONB,

  PRIMARY KEY (ts, id),
  CONSTRAINT telemetry_events_action_chk
    CHECK (action IS NULL OR action IN ('read','append','update','delete')),
  CONSTRAINT telemetry_events_event_kind_chk
    CHECK (event_kind IN (
      'intent_received','intent_authorized','intent_routed',
      'plan_compiled','plan_rejected',
      'execution_started','execution_finished','artifact_emitted',
      'source_health','source_drift','agent_rate_limited'
    )),
  CONSTRAINT telemetry_events_status_chk
    CHECK (status IS NULL OR status IN (
      'ok','denied','over_budget','circuit_open','plan_error','exec_error'
    )),
  CONSTRAINT telemetry_events_connector_kind_chk
    CHECK (connector_kind IS NULL OR connector_kind IN
      ('mysql','postgres','iceberg','duckdb','rag','model','file','snowflake','mssql')),
  CONSTRAINT telemetry_events_latency_nonneg
    CHECK (latency_ms IS NULL OR latency_ms >= 0),
  CONSTRAINT telemetry_events_bytes_nonneg
    CHECK (
      (est_bytes    IS NULL OR est_bytes    >= 0)
      AND (actual_bytes IS NULL OR actual_bytes >= 0)
    )
) PARTITION BY RANGE (ts);

CREATE INDEX telemetry_events_brin_ts_idx
  ON eh_operational.telemetry_events USING BRIN (ts);

CREATE INDEX telemetry_events_tenant_ts_idx
  ON eh_operational.telemetry_events (tenant_id, ts DESC);

CREATE INDEX telemetry_events_agent_kind_idx
  ON eh_operational.telemetry_events (agent_id, event_kind);

CREATE INDEX telemetry_events_connector_kind_idx
  ON eh_operational.telemetry_events (connector_kind, event_kind);

COMMENT ON TABLE eh_operational.telemetry_events
  IS 'Unified telemetry stream — one dimensioned schema for all components, all connectors. Slicing by agent / source / connector_kind / entity / action is a query, not a separate table.';

CREATE TABLE eh_operational.telemetry_events_2026_05
  PARTITION OF eh_operational.telemetry_events
  FOR VALUES FROM ('2026-05-01 00:00:00+00') TO ('2026-06-01 00:00:00+00');

CREATE TABLE eh_operational.telemetry_events_default
  PARTITION OF eh_operational.telemetry_events
  DEFAULT;

-- 2. source_health
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.source_health (
  id              UUID         NOT NULL,
  ts              TIMESTAMPTZ  NOT NULL DEFAULT now(),
  source_id       UUID         NOT NULL,
  state           TEXT         NOT NULL,
  latency_ms      INT,
  error_message   TEXT,

  PRIMARY KEY (id),
  CONSTRAINT source_health_state_chk
    CHECK (state IN ('healthy','degraded','unhealthy','unknown')),
  CONSTRAINT source_health_latency_nonneg
    CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX source_health_source_ts_idx
  ON eh_operational.source_health (source_id, ts DESC);

CREATE INDEX source_health_brin_ts_idx
  ON eh_operational.source_health USING BRIN (ts);

COMMENT ON TABLE eh_operational.source_health
  IS 'Rolling health snapshots per source. Append-only.';

-- 3. schema_snapshots
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.schema_snapshots (
  id               UUID         NOT NULL,
  ts               TIMESTAMPTZ  NOT NULL DEFAULT now(),
  source_id        UUID         NOT NULL,
  schema_payload   JSONB        NOT NULL,
  schema_hash      TEXT         NOT NULL,

  PRIMARY KEY (id),
  CONSTRAINT schema_snapshots_hash_format
    CHECK (schema_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX schema_snapshots_source_ts_idx
  ON eh_operational.schema_snapshots (source_id, ts DESC);

CREATE INDEX schema_snapshots_hash_idx
  ON eh_operational.schema_snapshots (source_id, schema_hash);

COMMENT ON TABLE eh_operational.schema_snapshots
  IS 'Physical schema crawled from each source. Drift detector compares latest snapshots to declared schema (Phase 11).';

-- 4. cost_records
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.cost_records (
  id                  UUID         NOT NULL,
  ts                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  tenant_id           UUID         NOT NULL,
  agent_id            UUID         NOT NULL,
  source_id           UUID         NOT NULL,
  est_bytes           BIGINT,
  actual_bytes        BIGINT,
  est_cost_cents      BIGINT,
  actual_cost_cents   BIGINT,

  PRIMARY KEY (id),
  CONSTRAINT cost_records_bytes_nonneg
    CHECK (
      (est_bytes        IS NULL OR est_bytes        >= 0)
      AND (actual_bytes IS NULL OR actual_bytes     >= 0)
    ),
  CONSTRAINT cost_records_cost_nonneg
    CHECK (
      (est_cost_cents    IS NULL OR est_cost_cents    >= 0)
      AND (actual_cost_cents IS NULL OR actual_cost_cents >= 0)
    )
);

CREATE INDEX cost_records_tenant_ts_idx
  ON eh_operational.cost_records (tenant_id, ts DESC);

CREATE INDEX cost_records_agent_ts_idx
  ON eh_operational.cost_records (agent_id, ts DESC);

CREATE INDEX cost_records_source_ts_idx
  ON eh_operational.cost_records (source_id, ts DESC);

CREATE INDEX cost_records_brin_ts_idx
  ON eh_operational.cost_records USING BRIN (ts);

COMMENT ON TABLE eh_operational.cost_records
  IS 'Per-intent cost ledger. Drives cost dashboards and budget enforcement (Phase 9).';

-- 5. proposals
-- ----------------------------------------------------------------------------

CREATE TABLE eh_operational.proposals (
  id                UUID         NOT NULL,
  ts                TIMESTAMPTZ  NOT NULL DEFAULT now(),
  tenant_id         UUID         NOT NULL,
  proposal_kind     TEXT         NOT NULL,
  payload           JSONB        NOT NULL,
  status            TEXT         NOT NULL DEFAULT 'pending',

  PRIMARY KEY (id),
  CONSTRAINT proposals_kind_chk
    CHECK (proposal_kind IN ('materialized_view','routing_rule','cost_optimization','schema_drift_fix')),
  CONSTRAINT proposals_status_chk
    CHECK (status IN ('pending','approved','rejected','applied'))
);

CREATE INDEX proposals_tenant_status_ts_idx
  ON eh_operational.proposals (tenant_id, status, ts DESC);

COMMENT ON TABLE eh_operational.proposals
  IS 'Async copilot output awaiting operator review (Phase 13). Status transitions are append-only — a status change is a NEW row referencing the original via attrs.original_id.';
-- ----------------------------------------------------------------------------
-- END 0010_operational_other.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0011_rls_policies.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0011 — Row-level security (RLS) policies
-- ============================================================================
-- Defense-in-depth on top of the schema-level grants. The application sets
-- app.tenant_id (and app.agent_id) via SET LOCAL inside its request
-- transaction; these policies filter rows accordingly.
--
-- eh_admin bypasses RLS (it's the operator escape hatch).
-- eh_service is subject to all RLS policies.
--
-- Reference: architecture §5.8, §5.10, §8.
-- ============================================================================

-- Helper: a stable function returning the current tenant from the GUC.
-- Marked STABLE so it can be used in policy expressions efficiently.
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION eh_control.current_tenant_id() RETURNS UUID AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::UUID;
$$ LANGUAGE SQL STABLE SECURITY INVOKER;

COMMENT ON FUNCTION eh_control.current_tenant_id()
  IS 'Returns the tenant_id from the per-request session GUC app.tenant_id. NULL if unset (request rejected by upstream guard before reaching SQL).';

-- ============================================================================
-- 1. eh_control — tenant-scoped tables
-- ============================================================================

-- 1.1 tenants — eh_service can read its own row only.
ALTER TABLE eh_control.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.tenants FORCE ROW LEVEL SECURITY;

CREATE POLICY tenants_select_own ON eh_control.tenants
  FOR SELECT TO eh_service
  USING (id = eh_control.current_tenant_id());

-- 1.2 agents — scoped by tenant_id.
ALTER TABLE eh_control.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.agents FORCE ROW LEVEL SECURITY;

CREATE POLICY agents_select_tenant ON eh_control.agents
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

-- 1.3 agent_secrets — scoped via agent ownership.
ALTER TABLE eh_control.agent_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.agent_secrets FORCE ROW LEVEL SECURITY;

CREATE POLICY agent_secrets_select_tenant ON eh_control.agent_secrets
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.agents a
      WHERE a.id = agent_secrets.agent_id
        AND a.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.4 policies — scoped by tenant_id.
ALTER TABLE eh_control.policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.policies FORCE ROW LEVEL SECURITY;

CREATE POLICY policies_select_tenant ON eh_control.policies
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

-- 1.5 capabilities — scoped via agent ownership.
ALTER TABLE eh_control.capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.capabilities FORCE ROW LEVEL SECURITY;

CREATE POLICY capabilities_select_tenant ON eh_control.capabilities
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.agents a
      WHERE a.id = capabilities.agent_id
        AND a.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.6 sources — scoped by tenant_id.
ALTER TABLE eh_control.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.sources FORCE ROW LEVEL SECURITY;

CREATE POLICY sources_select_tenant ON eh_control.sources
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

-- 1.7 source_credentials — scoped via source.tenant.
ALTER TABLE eh_control.source_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.source_credentials FORCE ROW LEVEL SECURITY;

CREATE POLICY source_credentials_select_tenant ON eh_control.source_credentials
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.sources s
      WHERE s.id = source_credentials.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.8 source_<kind> tables — scoped via source.tenant.
-- One policy per per-kind table. Pattern is identical; we write them out so
-- behaviour is auditable per-table.
-- ----------------------------------------------------------------------------

DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'source_mysql',
    'source_postgres',
    'source_iceberg',
    'source_duckdb',
    'source_rag',
    'source_model',
    'source_file',
    'source_snowflake',
    'source_mssql'
  ]) LOOP
    EXECUTE format('ALTER TABLE eh_control.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('ALTER TABLE eh_control.%I FORCE ROW LEVEL SECURITY;', t);
    EXECUTE format(
      'CREATE POLICY %I_select_tenant ON eh_control.%I FOR SELECT TO eh_service USING (EXISTS (SELECT 1 FROM eh_control.sources s WHERE s.id = %I.source_id AND s.tenant_id = eh_control.current_tenant_id()));',
      t, t, t
    );
  END LOOP;
END
$$;

-- 1.8a source_duckdb_extensions — scoped via source_duckdb → source → tenant.
ALTER TABLE eh_control.source_duckdb_extensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.source_duckdb_extensions FORCE ROW LEVEL SECURITY;

CREATE POLICY source_duckdb_extensions_select_tenant ON eh_control.source_duckdb_extensions
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1
      FROM eh_control.source_duckdb sd
      JOIN eh_control.sources s ON s.id = sd.source_id
      WHERE sd.source_id = source_duckdb_extensions.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.9 entities — scoped by tenant_id.
ALTER TABLE eh_control.entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entities FORCE ROW LEVEL SECURITY;

CREATE POLICY entities_select_tenant ON eh_control.entities
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

-- 1.10 entity_fields — scoped via entity.tenant.
ALTER TABLE eh_control.entity_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entity_fields FORCE ROW LEVEL SECURITY;

CREATE POLICY entity_fields_select_tenant ON eh_control.entity_fields
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.entities e
      WHERE e.id = entity_fields.entity_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.11 entity_bindings — scoped via entity.tenant.
ALTER TABLE eh_control.entity_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entity_bindings FORCE ROW LEVEL SECURITY;

CREATE POLICY entity_bindings_select_tenant ON eh_control.entity_bindings
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.entities e
      WHERE e.id = entity_bindings.entity_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.11a entity_binding_actions — scoped via binding → entity → tenant.
ALTER TABLE eh_control.entity_binding_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entity_binding_actions FORCE ROW LEVEL SECURITY;

CREATE POLICY entity_binding_actions_select_tenant ON eh_control.entity_binding_actions
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1
      FROM eh_control.entity_bindings b
      JOIN eh_control.entities e ON e.id = b.entity_id
      WHERE b.id = entity_binding_actions.binding_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.12 entity_field_bindings — scoped via binding → entity → tenant.
ALTER TABLE eh_control.entity_field_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entity_field_bindings FORCE ROW LEVEL SECURITY;

CREATE POLICY entity_field_bindings_select_tenant ON eh_control.entity_field_bindings
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1
      FROM eh_control.entity_bindings b
      JOIN eh_control.entities e ON e.id = b.entity_id
      WHERE b.id = entity_field_bindings.binding_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.13 routing_rules — scoped via entity.tenant.
ALTER TABLE eh_control.routing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.routing_rules FORCE ROW LEVEL SECURITY;

CREATE POLICY routing_rules_select_tenant ON eh_control.routing_rules
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.entities e
      WHERE e.id = routing_rules.entity_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.14 predicate_nodes — scoped via rule → entity → tenant.
ALTER TABLE eh_control.predicate_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.predicate_nodes FORCE ROW LEVEL SECURITY;

CREATE POLICY predicate_nodes_select_tenant ON eh_control.predicate_nodes
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1
      FROM eh_control.routing_rules r
      JOIN eh_control.entities e ON e.id = r.entity_id
      WHERE r.id = predicate_nodes.rule_id
        AND e.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 1.15 entity_relationships — scoped opportunistically by from-side tenant
-- (relationships have no native tenant column; we accept reads where either
-- side's entity table indicates the current tenant).
-- ----------------------------------------------------------------------------

ALTER TABLE eh_control.entity_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_control.entity_relationships FORCE ROW LEVEL SECURITY;

-- Bare-minimum policy for V1: allow only relationships whose from_kind=='entity'
-- and from_id resolves to a same-tenant entity. Cross-kind queries from
-- eh_service are intentionally narrow in V1; expand in later phases.
CREATE POLICY entity_relationships_select_tenant ON eh_control.entity_relationships
  FOR SELECT TO eh_service
  USING (
    (from_kind = 'entity' AND EXISTS (
      SELECT 1 FROM eh_control.entities e
      WHERE e.id = entity_relationships.from_id
        AND e.tenant_id = eh_control.current_tenant_id()
    ))
    OR
    (to_kind = 'entity' AND EXISTS (
      SELECT 1 FROM eh_control.entities e
      WHERE e.id = entity_relationships.to_id
        AND e.tenant_id = eh_control.current_tenant_id()
    ))
  );

-- ============================================================================
-- 2. eh_operational — tenant-scoped tables (INSERT + SELECT)
-- ============================================================================
-- For inserts, the WITH CHECK clause enforces that the new row's tenant_id
-- matches the session GUC. For selects, the USING clause filters.
-- ============================================================================

-- 2.1 audit_log — partitioned parent; RLS attaches to the parent and
-- inherits to all current and future partitions.
ALTER TABLE eh_operational.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.audit_log FORCE ROW LEVEL SECURITY;

CREATE POLICY audit_log_tenant_select ON eh_operational.audit_log
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

CREATE POLICY audit_log_tenant_insert ON eh_operational.audit_log
  FOR INSERT TO eh_service
  WITH CHECK (tenant_id = eh_control.current_tenant_id());

-- 2.2 telemetry_events — partitioned parent.
ALTER TABLE eh_operational.telemetry_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.telemetry_events FORCE ROW LEVEL SECURITY;

CREATE POLICY telemetry_events_tenant_select ON eh_operational.telemetry_events
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

CREATE POLICY telemetry_events_tenant_insert ON eh_operational.telemetry_events
  FOR INSERT TO eh_service
  WITH CHECK (tenant_id = eh_control.current_tenant_id());

-- 2.3 source_health — scoped via source.tenant (no native tenant column).
ALTER TABLE eh_operational.source_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.source_health FORCE ROW LEVEL SECURITY;

CREATE POLICY source_health_tenant_select ON eh_operational.source_health
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.sources s
      WHERE s.id = source_health.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

CREATE POLICY source_health_tenant_insert ON eh_operational.source_health
  FOR INSERT TO eh_service
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM eh_control.sources s
      WHERE s.id = source_health.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 2.4 schema_snapshots — same pattern as source_health.
ALTER TABLE eh_operational.schema_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.schema_snapshots FORCE ROW LEVEL SECURITY;

CREATE POLICY schema_snapshots_tenant_select ON eh_operational.schema_snapshots
  FOR SELECT TO eh_service
  USING (
    EXISTS (
      SELECT 1 FROM eh_control.sources s
      WHERE s.id = schema_snapshots.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

CREATE POLICY schema_snapshots_tenant_insert ON eh_operational.schema_snapshots
  FOR INSERT TO eh_service
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM eh_control.sources s
      WHERE s.id = schema_snapshots.source_id
        AND s.tenant_id = eh_control.current_tenant_id()
    )
  );

-- 2.5 cost_records — has native tenant_id column.
ALTER TABLE eh_operational.cost_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.cost_records FORCE ROW LEVEL SECURITY;

CREATE POLICY cost_records_tenant_select ON eh_operational.cost_records
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

CREATE POLICY cost_records_tenant_insert ON eh_operational.cost_records
  FOR INSERT TO eh_service
  WITH CHECK (tenant_id = eh_control.current_tenant_id());

-- 2.6 proposals — has native tenant_id column.
ALTER TABLE eh_operational.proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE eh_operational.proposals FORCE ROW LEVEL SECURITY;

CREATE POLICY proposals_tenant_select ON eh_operational.proposals
  FOR SELECT TO eh_service
  USING (tenant_id = eh_control.current_tenant_id());

CREATE POLICY proposals_tenant_insert ON eh_operational.proposals
  FOR INSERT TO eh_service
  WITH CHECK (tenant_id = eh_control.current_tenant_id());

-- ============================================================================
-- Note on eh_admin:
-- eh_admin role does NOT have BYPASSRLS by default. To keep operator inspection
-- unconstrained, the operator can either (a) issue 'SET LOCAL row_security =
-- off' within their admin session, or (b) the operator can choose to ALTER
-- ROLE eh_admin BYPASSRLS (deferred decision — not done here so the deployment
-- defaults to maximum safety). This deliberate choice keeps the door open
-- without committing the project to bypass.
-- ============================================================================
-- ----------------------------------------------------------------------------
-- END 0011_rls_policies.sql
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- BEGIN 0012_source_auth_extension.sql
-- ----------------------------------------------------------------------------
-- ============================================================================
-- 0012 — Source auth-kind extension (mysql, postgres)
-- ============================================================================
-- Bring source_mysql and source_postgres to the same auth_kind pattern that
-- source_snowflake / source_mssql / source_iceberg already use. Password is
-- no longer the only path — mTLS and IAM auth are first-class.
--
-- Per-kind required-field invariants are enforced by a shape CHECK so the
-- engine refuses invalid combinations at insert time (zero-trust §12).
--
-- Backward compatibility: auth_kind defaults to 'password', so existing
-- rows (none yet — schema not applied to a live store) and any future
-- password-style inserts continue to work without code changes.
--
-- Reference: SCHEMA.md §3.7.1, §3.7.2. Architecture §5.6.
-- ============================================================================

-- ============================================================================
-- 1. source_mysql
-- ============================================================================

ALTER TABLE eh_control.source_mysql
  ALTER COLUMN password_secret_ref DROP NOT NULL,
  ADD COLUMN auth_kind            TEXT NOT NULL DEFAULT 'password',
  ADD COLUMN tls_cert_secret_ref  TEXT,
  ADD COLUMN tls_key_secret_ref   TEXT,
  ADD COLUMN tls_ca_secret_ref    TEXT,
  ADD COLUMN iam_role_arn         TEXT,
  ADD COLUMN iam_service_account  TEXT;

ALTER TABLE eh_control.source_mysql
  ADD CONSTRAINT source_mysql_auth_kind_chk
    CHECK (auth_kind IN ('password','mtls','iam_aws','iam_gcp'));

ALTER TABLE eh_control.source_mysql
  ADD CONSTRAINT source_mysql_tls_secret_ref_scheme
    CHECK (
      (tls_cert_secret_ref IS NULL OR tls_cert_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
      AND
      (tls_key_secret_ref  IS NULL OR tls_key_secret_ref  ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
      AND
      (tls_ca_secret_ref   IS NULL OR tls_ca_secret_ref   ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
    );

ALTER TABLE eh_control.source_mysql
  ADD CONSTRAINT source_mysql_auth_shape_chk CHECK (
    (
      auth_kind = 'password'
      AND password_secret_ref IS NOT NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'mtls'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NOT NULL
      AND tls_key_secret_ref  IS NOT NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'iam_aws'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NOT NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'iam_gcp'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NOT NULL
    )
  );

COMMENT ON COLUMN eh_control.source_mysql.auth_kind
  IS 'Authentication mode: password (default) | mtls | iam_aws | iam_gcp. Extending this enum is an operator-approved migration.';
COMMENT ON COLUMN eh_control.source_mysql.tls_cert_secret_ref
  IS 'Secrets-manager reference to client TLS certificate (PEM) for auth_kind=mtls.';
COMMENT ON COLUMN eh_control.source_mysql.tls_key_secret_ref
  IS 'Secrets-manager reference to client TLS private key (PEM) for auth_kind=mtls.';
COMMENT ON COLUMN eh_control.source_mysql.tls_ca_secret_ref
  IS 'Secrets-manager reference to CA certificate for ssl_mode=verify_ca / verify_identity. Optional; orthogonal to auth_kind.';
COMMENT ON COLUMN eh_control.source_mysql.iam_role_arn
  IS 'AWS IAM role ARN for RDS IAM authentication when auth_kind=iam_aws.';
COMMENT ON COLUMN eh_control.source_mysql.iam_service_account
  IS 'GCP service account email for Cloud SQL IAM authentication when auth_kind=iam_gcp.';

-- ============================================================================
-- 2. source_postgres
-- ============================================================================

ALTER TABLE eh_control.source_postgres
  ALTER COLUMN password_secret_ref DROP NOT NULL,
  ADD COLUMN auth_kind            TEXT NOT NULL DEFAULT 'password',
  ADD COLUMN tls_cert_secret_ref  TEXT,
  ADD COLUMN tls_key_secret_ref   TEXT,
  ADD COLUMN tls_ca_secret_ref    TEXT,
  ADD COLUMN iam_role_arn         TEXT,
  ADD COLUMN iam_service_account  TEXT;

ALTER TABLE eh_control.source_postgres
  ADD CONSTRAINT source_postgres_auth_kind_chk
    CHECK (auth_kind IN ('password','mtls','iam_aws','iam_gcp'));

ALTER TABLE eh_control.source_postgres
  ADD CONSTRAINT source_postgres_tls_secret_ref_scheme
    CHECK (
      (tls_cert_secret_ref IS NULL OR tls_cert_secret_ref ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
      AND
      (tls_key_secret_ref  IS NULL OR tls_key_secret_ref  ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
      AND
      (tls_ca_secret_ref   IS NULL OR tls_ca_secret_ref   ~ '^(vault|k8s|aws-sm|gcp-sm|file|env)://')
    );

ALTER TABLE eh_control.source_postgres
  ADD CONSTRAINT source_postgres_auth_shape_chk CHECK (
    (
      auth_kind = 'password'
      AND password_secret_ref IS NOT NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'mtls'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NOT NULL
      AND tls_key_secret_ref  IS NOT NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'iam_aws'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NOT NULL
      AND iam_service_account IS NULL
    )
    OR
    (
      auth_kind = 'iam_gcp'
      AND password_secret_ref IS NULL
      AND tls_cert_secret_ref IS NULL
      AND tls_key_secret_ref  IS NULL
      AND iam_role_arn        IS NULL
      AND iam_service_account IS NOT NULL
    )
  );

COMMENT ON COLUMN eh_control.source_postgres.auth_kind
  IS 'Authentication mode: password (default) | mtls | iam_aws | iam_gcp. Extending this enum is an operator-approved migration.';
COMMENT ON COLUMN eh_control.source_postgres.tls_cert_secret_ref
  IS 'Secrets-manager reference to client TLS certificate (PEM) for auth_kind=mtls.';
COMMENT ON COLUMN eh_control.source_postgres.tls_key_secret_ref
  IS 'Secrets-manager reference to client TLS private key (PEM) for auth_kind=mtls.';
COMMENT ON COLUMN eh_control.source_postgres.tls_ca_secret_ref
  IS 'Secrets-manager reference to CA certificate for ssl_mode=verify-ca / verify-full. Optional; orthogonal to auth_kind.';
COMMENT ON COLUMN eh_control.source_postgres.iam_role_arn
  IS 'AWS IAM role ARN for RDS IAM authentication when auth_kind=iam_aws.';
COMMENT ON COLUMN eh_control.source_postgres.iam_service_account
  IS 'GCP service account email for Cloud SQL IAM authentication when auth_kind=iam_gcp.';
-- ----------------------------------------------------------------------------
-- END 0012_source_auth_extension.sql
-- ----------------------------------------------------------------------------

-- ============================================================================
-- End of unified schema. Apply 0013_set_role_passwords.sh next for role
-- password attachment.
-- ============================================================================
